// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.DAL;

namespace Projekt.DAL.Migrations
{
    [DbContext(typeof(LigaDbContext))]
    [Migration("20210603205749_UpdejtSlike")]
    partial class UpdejtSlike
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projekt.Model.Igrac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlubId")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalnost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferiranaNoga")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<float>("VrijednostUMilijunima")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("Projekt.Model.Klub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojBodova")
                        .HasColumnType("int");

                    b.Property<int>("BrojTrofeja")
                        .HasColumnType("int");

                    b.Property<int>("GodinaOsnutka")
                        .HasColumnType("int");

                    b.Property<int>("GolRazlika")
                        .HasColumnType("int");

                    b.Property<string>("ImeKluba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trener")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idSlike")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idSlike");

                    b.ToTable("Klubovi");
                });

            modelBuilder.Entity("Projekt.Model.Slika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivSlike")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PodaciSlike")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Slika");
                });

            modelBuilder.Entity("Projekt.Model.Igrac", b =>
                {
                    b.HasOne("Projekt.Model.Klub", "Klub")
                        .WithMany("IgraciKluba")
                        .HasForeignKey("KlubId");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Projekt.Model.Klub", b =>
                {
                    b.HasOne("Projekt.Model.Slika", "Slika")
                        .WithMany()
                        .HasForeignKey("idSlike");

                    b.Navigation("Slika");
                });

            modelBuilder.Entity("Projekt.Model.Klub", b =>
                {
                    b.Navigation("IgraciKluba");
                });
#pragma warning restore 612, 618
        }
    }
}
