// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.DAL;

namespace Projekt.DAL.Migrations
{
    [DbContext(typeof(LigaDbContext))]
    [Migration("20210603183418_Inicijalna")]
    partial class Inicijalna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projekt.Model.Igrac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalnost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferiranaNoga")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<float>("VrijednostUMilijunima")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("Projekt.Model.Klub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojBodova")
                        .HasColumnType("int");

                    b.Property<int>("BrojTrofeja")
                        .HasColumnType("int");

                    b.Property<int>("GodinaOsnutka")
                        .HasColumnType("int");

                    b.Property<int>("GolRazlika")
                        .HasColumnType("int");

                    b.Property<string>("ImeKluba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trener")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klubovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojBodova = 85,
                            BrojTrofeja = 38,
                            GodinaOsnutka = 1911,
                            GolRazlika = 56,
                            ImeKluba = "GNK Dinamo Zagreb",
                            Stadion = "Maksimir",
                            Trener = "Damir Krznar"
                        },
                        new
                        {
                            Id = 2,
                            BrojBodova = 77,
                            BrojTrofeja = 1,
                            GodinaOsnutka = 1947,
                            GolRazlika = 34,
                            ImeKluba = "NK Osijek",
                            Stadion = "Gradski Vrt",
                            Trener = "Nenad Bjelica"
                        },
                        new
                        {
                            Id = 3,
                            BrojBodova = 61,
                            BrojTrofeja = 7,
                            GodinaOsnutka = 1946,
                            GolRazlika = 5,
                            ImeKluba = "HNK Rijeka",
                            Stadion = "Rujevica",
                            Trener = "Goran Tomić"
                        },
                        new
                        {
                            Id = 4,
                            BrojBodova = 60,
                            BrojTrofeja = 14,
                            GodinaOsnutka = 1911,
                            GolRazlika = 11,
                            ImeKluba = "HNK Hajduk Split",
                            Stadion = "Poljud",
                            Trener = "Jens Gustafsson"
                        },
                        new
                        {
                            Id = 5,
                            BrojBodova = 59,
                            BrojTrofeja = 0,
                            GodinaOsnutka = 2009,
                            GolRazlika = 13,
                            ImeKluba = "HNK Gorica",
                            Stadion = "SRC Velika Gorica",
                            Trener = "Krunoslav Rendulić"
                        },
                        new
                        {
                            Id = 6,
                            BrojBodova = 35,
                            BrojTrofeja = 0,
                            GodinaOsnutka = 1932,
                            GolRazlika = -15,
                            ImeKluba = "HNK Šibenik",
                            Stadion = "Šubićevac",
                            Trener = "Ivan Močinić"
                        },
                        new
                        {
                            Id = 7,
                            BrojBodova = 34,
                            BrojTrofeja = 0,
                            GodinaOsnutka = 1907,
                            GolRazlika = -17,
                            ImeKluba = "NK Slaven Belupo Koprivnica",
                            Stadion = "Gradski stadion Ivan Kušek-Apaš",
                            Trener = "Tomislav Stipić"
                        },
                        new
                        {
                            Id = 8,
                            BrojBodova = 30,
                            BrojTrofeja = 0,
                            GodinaOsnutka = 1914,
                            GolRazlika = -31,
                            ImeKluba = "NK Lokomotiva Zagreb",
                            Stadion = "Kranjčevićeva",
                            Trener = ""
                        },
                        new
                        {
                            Id = 9,
                            BrojBodova = 29,
                            BrojTrofeja = 0,
                            GodinaOsnutka = 1948,
                            GolRazlika = -25,
                            ImeKluba = "NK Istra 1961",
                            Stadion = "Aldo Drosina",
                            Trener = "Danijel Jumić"
                        },
                        new
                        {
                            Id = 10,
                            BrojBodova = 28,
                            BrojTrofeja = 0,
                            GodinaOsnutka = 2012,
                            GolRazlika = -31,
                            ImeKluba = "NK Varaždin",
                            Stadion = "Stadion Varteks",
                            Trener = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
